from datetime import datetime
from . import db
from enum import Enum

class OrderStatus(str, Enum):
    PENDING = "Pending"
    PACKAGED = "Packaged"
    PICKED = "Picked"
    TRANSIT = "Transit"
    DELIVERED = "Delivered"
    FAILED = "Failed"

    @classmethod
    def values(cls):
        return [s.value for s in cls]

class Order(db.Model):
    __tablename__ = "orders"

    id = db.Column(db.Integer, primary_key=True)

    # 4-character unique code (e.g. "HU2G") — NOT a UUID. Generated by
    # order_service.generate_order_id() from a 33-character pool
    # (digits 1-9, A-Z minus I/O to avoid 1/0 confusion), no repeated
    # characters within one code, checked against existing rows before
    # save (see that function's docstring for the full generation +
    # collision-retry logic). Column stays comfortably wider than 4
    # chars so nothing breaks if the format ever changes later.
    order_id = db.Column(db.String(40), unique=True, nullable=False)

    # Nullable — an order can be placed by a guest (no account) or a
    # logged-in user. Guest orders are still fully identified by the
    # customer_name/phone/address fields below regardless of user_id.
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True)

    customer_name = db.Column(db.String(200), nullable=False)
    phone = db.Column(db.String(40), nullable=True)
    address = db.Column(db.Text, nullable=True)

    # Optional social contact info, e.g. for delivery coordination.
    social_platform = db.Column(db.String(40), nullable=True)  # WhatsApp, Instagram, Facebook, TikTok
    social_handle = db.Column(db.String(100), nullable=True)

    # Shipping zone drives shipping_fee — see order_service.py's
    # SHIPPING_FEES mapping for the authoritative fee-per-zone values.
    # Stored (not recomputed later) so a future fee change never alters
    # the amount actually charged on a historical order. Three zones
    # (confirmed): inside_dhaka (৳70), outside_dhaka (৳140), sub_city
    # (৳70).
    #
    # This column is ALSO what Hasan calls "delivery_charge" in the
    # admin dashboard/wholesale-style editing — same field, not a
    # separate one (confirmed): the admin can overwrite this value
    # directly on an existing order (e.g. correcting it, or reflecting
    # extra advance collected), and total is recalculated from
    # payment_type + this field whenever either changes — see
    # recompute_total() below.
    shipping_zone = db.Column(db.String(40), nullable=False, default="inside_dhaka")
    shipping_fee = db.Column(db.Float, nullable=False, default=70.0)

    # How the delivery_charge (shipping_fee) above relates to the total
    # the customer owes / the delivery man collects — chosen by the
    # CUSTOMER at checkout, editable by the admin afterward. Three
    # states (confirmed):
    #   "postpaid"  -> total = subtotal + shipping_fee (delivery paid
    #                  to the courier on arrival, on top of the items)
    #   "prepaid"   -> total = subtotal (delivery already settled
    #                  separately/upfront, not added again)
    #   "included"  -> total = subtotal - shipping_fee (delivery cost
    #                  was folded into subtotal as extra advance
    #                  collected, so it's subtracted back out to get
    #                  the real item total). "included" always implies
    #                  prepaid — there is no "included"+"postpaid"
    #                  combination (confirmed).
    # See order_service.recompute_total() — the single place this
    # formula lives, called both at checkout and whenever the admin
    # edits shipping_fee/payment_type afterward, so the two paths can
    # never drift out of sync with each other.
    payment_type = db.Column(db.String(20), nullable=False, default="postpaid")

    payment_method = db.Column(db.String(40), nullable=False, default="cod")  # "bkash" | "nagad" | "cod"
    transaction_id = db.Column(db.String(120), nullable=True)
    payment_number = db.Column(db.String(60), nullable=True)

    status = db.Column(db.String(20), nullable=False, default=OrderStatus.PENDING.value)

    # Courier tracking URL — admin pastes/edits it manually (no courier
    # API integration, per Hasan's confirmed decision). Shown to BOTH
    # the admin dashboard and the customer-facing order history page
    # (see routes/account_route.py / templates/orders.html), so it's
    # included in to_dict() unconditionally — nothing sensitive in a
    # tracking URL.
    tracking_link = db.Column(db.String(500), nullable=True)

    # subtotal = sum of line items only, BEFORE shipping — kept alongside
    # `total` so the dashboard/receipt can show a shipping-fee breakdown
    # without recomputing it from items every time.
    subtotal = db.Column(db.Float, nullable=False, default=0.0)
    total = db.Column(db.Float, nullable=False, default=0.0)

    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    items = db.relationship("OrderItem", back_populates="order", cascade="all, delete-orphan")
    user = db.relationship("User", back_populates="orders")

    def to_dict(self, include_items=False):
        data = {
            "order_id": self.order_id,
            "customer_name": self.customer_name,
            "phone": self.phone,
            "address": self.address,
            "social_platform": self.social_platform,
            "social_handle": self.social_handle,
            "shipping_zone": self.shipping_zone,
            "shipping_fee": self.shipping_fee,
            "payment_type": self.payment_type,
            "payment_method": self.payment_method,
            "transaction_id": self.transaction_id,
            "payment_number": self.payment_number,
            "status": self.status,
            "tracking_link": self.tracking_link,
            "subtotal": self.subtotal,
            "total": self.total,
            # Same value as `total` — duplicated under this name only
            # so the customer-facing order page can label it explicitly
            # as "Pay the delivery man" without every caller needing to
            # know that total IS that number (confirmed: no separate
            # 3rd number exists here, it's total under a clearer label).
            "collect_on_delivery": self.total,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }
        if include_items:
            data["items"] = [item.to_dict() for item in self.items]
        return data

